---
# output: github_document
output: 
  pdf_document:
    keep_tex: true
    fig_caption: true
    latex_engine: pdflatex
    template: svm-latex-ms.tex
    number_sections: true
title: | 
        | Manuscrito de Biogeografía
        | 
         
author: Estudiante de Biogeografía
- name: Nombre de el/la estudiante
  affiliation: Joseé Abreu Díaz "Estudiante, Universidad Autónoma de Santo Domingo (UASD)"
abstract: "Resumen del manuscrito"
keywords: "palabra clave 1, palabra clave 2"
date: "`r format(Sys.time(), '%B %d, %Y')`"
geometry: margin=1in
fontfamily: mathpazo
fontsize: 11pt
# spacing: double
bibliography: bibliography.bib
# csl: plos-one.csl
csl: apa.csl
header-includes:
  \usepackage{pdflscape}
  \newcommand{\blandscape}{\begin{landscape}}
  \newcommand{\elandscape}{\end{landscape}}
  \usepackage{float} \floatplacement{figure}{H} 
  \newcommand{\beginsupplement}{
    \setcounter{table}{0}
    \renewcommand{\thetable}{S\arabic{table}}
    \setcounter{figure}{0}
    \renewcommand{\thefigure}{S\arabic{figure}}
    }
---

# Introducción

 Así como puede estar integrada una familia convencional, también las familias de plantas presentan unos criterios de agrupación que hacen de cada grupo botánico, verdaderas unidades identificables [@van2010biodiversidad].
Los senderos a seguir nos podrían encaminar por un sinfín de 
rutas alternativas, según, @van2010biodiversidad, la flora del estado de Sonora con un área de 184934 km2, actualmente tiene 3652 taxones específicos e intraespecíficos en 188 familias y 1103 géneros. 
La organización de las plantas en familias constituye una respuesta específica al orden en que la ecología, como ciencia que estudia las categorías agrupacionales que presentan los organismos en sus interacciones [@margalef1977ecologia], ordena las unidades de grupos de plantas.
Viendo que la ecología es la forma sistemática de estudiar las diversas dimensiones que resultan de la interacción entre organismos diversos, nos apoyamos en la biogeografía, con la intención de conocer los emplazamientos que ocupan esos grupos de organismos, especialmente de plantas.
En este manuscrito se pretende dar a conocer los aspectos fundamentales de la familia de plantas conocida como Moraceae, partiendo del estudio de gráficos, tablas y diagramas procedentes de invstigaciones realizadas en la Isla Barro Colorado, en Panamá.
Según, @clement2009morphological, la familia Moracea comprende 37 géneros y aproximadamente 1100 especies en regiones tropicales y templadas en todo el mundo. En América se aprecia una amplia dsitribución de las especies de esta familia, como lo es en el territorio de México, en las zonas de Sinaloa, o Chiapas, siendo de gran importancia para la comunidad de frugivoros que se alimentan de las mismas. 
Entre las especies reconocidas, se destacan: Brosimun alicastrum, Maclura tinctoria, Ficus mexicana, Ficus petiolaris, Ficus cotinifolia, Ficus spp. De esta misma distribución existen importantes trabajos, como son: @magallanesdistribucion, y @piedra2006genero. 
En ese orden pretendo identificar otras zonas del mundo donde podrían existir ejemplares de estas plantas correspondientes a los tipos de especies, y cuáles zonas presentan condiciones favorables para el predominio de las mismas, partiendo del análisis de los trabajos realizados en Isla Barro Colorado.
# Metodología
Apoyándome en los trabajos realizados en la Isla de Barro Colorado, mediante un anális inductivo, pretendo dar a conocer los datos estadísticos más pertinentes sobre la familia de plantas conocidas como Moraceas. Dejando claro que en otras zonas del continente existen importantes trabajos sobre esta familia de plantas, susceptibles de estudios debido en gran parte al soporte que constituyen en la alimentación de una amplia comunidad de frugívoros. Tomando como escenario esa pequeña isla del istmo de Panamá, empleando un serie de recursos que han derivado de profundas investigaciones, intento dar a conocer una nueva fisonomía a esta familia de plantas, o por lo menos crear algo nuevo para quienes consumen este tipo de artículos.
La isla de Barro Colorado se formó tras la creación del lago Gatún en 1913, durante la construcción del Canal de Panamá (1904-1914), la isla de 15 kilómetros cuadrados, alberga una de las estaciones más antiguas de investigación tropical del mundo donde se han llevado a cabo estudios por más de 100 años.  
La Isla Barro Colorado o BCI, por sus siglas en inglés, es uno de los puntos geográficos más estudiados en el mundo, es como una especie de Meca para los investigadores que quieren desarrollar allí sus estudios, muchas veces acompañados de sus estudiantes, estudiantes que en lo adelante también realizarán sus propias investigaciones por separado. En dicha isla todo está registrado, cada comunidad de insectos, plantas y otros animales, están debidamente mapeados, con inscripciones por doquier. Tal vez por la Amplia diversidad de orgaismos que allí predominana, se hace esta clase de inferencia en esta isla que se ha convertido en un laboratorio global, y ese es el caso que me compete, seguir ese pequeño trillo prar llegar a grandes verdades que requieren de una cantidad de recursos unaudita y tiempo, por el momento no disponibles si nos embarcaramos en hacer un itinerario parecido al de Darwin o el de Humboldt. Algunos estudios como los de @fredericksenbibosi, resaltan la importancia de las moraceae en el sentido de que sirven de alimentos a una amlpia comunidad de frugivoros, pero los cierto es que también tienen gran importancia en el sector maderero.

Este es el escenario para nuestro estudio:




\ldots

# Resultados

\ldots

# Discusión

# Agradecimientos

# Información de soporte

\ldots

# *Script* reproducible

\ldots

# Referencias
